function createfigure(yvector1)
%CREATEFIGURE(YVECTOR1)
%  YVECTOR1:  bar yvector

%  Auto-generated by MATLAB on 12-Jan-2017 13:41:54

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'XTickLabel',{'RtES','RlES','RGMA','RGMe','RTFL','RBF','REO','RIO','LtES','LlES','LGMA','LGME','LTFL','LBF','LEO','LIO'},...
    'XTick',[1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16],...
    'TickDir','out');
hold(axes1,'on');

% Create bar
bar(yvector1);

